### ISSUE TITLE
Background location updates

### ISSUE THREAD

**Issue by mharizanov** [owntracks/android#86]
I have it running on Android Lollipop Nexus 5 (but same issue was while I was running Kitkat).

Connection is fine and shows "Connected"; I have a always-on 3G plan so it is on constantly.

Automatic location Reporting=true
Reporting Interval=15
Include battery=true

Notifications -> All checked

Autostart=true
Locator displacement=50
Locator Interval=10
Locator background accuracy=Balanced
Locator Foreground accuracy=High power

If I open the application and hit the manual update, it does update; However doesnt not send update otherwise.

May be something related to power management while screen is off.

Cheers,
Martin

PS Great app, tons of potential. Kudos for the great work!

**Comment by jpmens** [comment]
Have you moved 'significantly' (i.e. more than, say, 1000m) to test this?

**Comment by mharizanov** [comment]
Yes, my daily commute is ~50km total, so moved quite a bit indeed.

**Comment by jpmens** [comment]
Only one update on my Nexus 4 over 25km; there is definitely something wrong. I admit I'm an iOS user and haven't driven Android since the last OS upgrade; I'll test again tomorrow.

**Comment by matbor** [comment]
My wifes was not updating as much (again - [https://github.com/owntracks/android/issues/66]) and I ended up removing the waypoint completely and it is updating more often now.  Not sure if it is related.

**Comment by jpmens** [comment]
There is definitely something wrong when running on latest Android. Very sparese updates. 
Do @binarybucks or @massimilianozilio know what's going on?

**Comment by mharizanov** [comment]
No,
Same here; This is why I raised the bug.

**Comment by binarybucks** [comment]
Not sure what changed. The Play Store Version is quite old and was not
changed for a longer time.
Maybe there were changes in the Play Services or other Android API foo.

I'm no longer carying an Android device for testing or debugging, so I
cannot check it at the moment.
Also I'm not very keen to adopt all the horrendous Android 5 APIs to be
honest.

On Tue, Jan 20, 2015 at 5:14 PM, mharizanov <notifications@github.com>
wrote:

> No,
> Same here; This is why I raised the bug.
> On 20 Jan 2015 18:13, "JP Mens" <notifications@github.com> wrote:
>
> > There is definitely something wrong when running on latest Android. Very
> > sparese updates.
> > Do @binarybucks <https://github.com/binarybucks> or @massimilianozilio
> > <https://github.com/massimilianozilio> know what's going on?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/owntracks/android/issues/86#issuecomment-70680135>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owntracks/android/issues/86#issuecomment-70680430>.
>



-- 
Mit freundlichen Grüßen / With kind regards
Alexander Rust

**Comment by mastix** [comment]
Having the same problem with my Samsung Galaxy S5 (Lollipop). Does not update anything when the screen is off... It updates without any problems, when I open the app. Maybe this has something to do with "Project Volta" which has been implemented with Android Lollipop? https://developer.android.com/about/versions/android-5.0.html#Power

Any news if OwnTracks (for Android) is still being developed?

**Comment by jpmens** [comment]
We're in dire need of someone to pick up development on the Android version. Care to pitch in? ;-)

Seriously, aside from a number of features our iOS app has which are missing or possibly desirable in the Android app, we urgently need to get this bug out in particular.

If anybody knows of an Android dev willing to help us, please yell.

**Comment by mastix** [comment]
Actually, I've been an Android developer... :) If I find some time next week, I'll look into it.

**Comment by binarybucks** [comment]
I think I might have an idea: The changelog of 5.0 states

The Context.bindService() method now requires an explicit Intent, and throws an exception if given an implicit intent. To ensure your app is secure, use an explicit intent when starting or binding your Service, and do not declare intent filters for the service.

So I guess the intend of the updated location is never received or the locator service is never registered in the first place (I think the later uses explicit intents looking at  https://github.com/owntracks/android/blob/master/src/main/java/st/alr/mqttitude/services/ServiceProxy.java#L202)



--
Alexander Rust

**Comment by binarybucks** [comment]
Oh, this might also correlate with Google breaking all location APIs with newer Play Services versions (6.5 onwards). Now we basically have to rewrite ServiceLocator.java because all API calls changed and behave differently.

Just replace in build.grade and try to compile. No quick fix in sight though. 
```
    compile 'com.google.android.gms:play-services:6.1.71'
```
by
```
    compile 'com.google.android.gms:play-services-maps:6.5.87'
    compile 'com.google.android.gms:play-services-location:6.5.87'
    compile 'com.google.android.gms:play-services-base:6.5.87'
```

It's nice that Android is moving forward but pushing a broken IDE, broken USB drives (yeah, thanks for that Google) and purging stable APIs all over the place is not especially encouraging for developers. 

I've pushed my incomplete and horribly broken ramblings for Android 5 compatibility to https://github.com/owntracks/android/tree/Android-5 for people to fix this mess. I've added issue #87 to track all broken things that came to my mind to discuss.

**Comment by mabnz** [comment]
I'm having the same problem on Android 4.4.4. So much so, I set locator displacement=50m, locator interval=1, and the map (and updates via MQTT) have still not updated after 4 hours. There definitely seems to be a problem.

**Comment by binarybucks** [comment]
That's good to know, so we can rule out a change in OS behaviour. 

As the version from Google Play was not updated for some time and it was working fine some time ago something outside the app must have changed. The only thing I can think of are the Play Services.

Tbh I don't really understand versioning here. When you compile an app, you link it against a specific Play Services (PS) version that provides e.g a location API. When you install the app and the PS on the device are older, the app refuses to run and prompts you to update the PS on the device. 

Now, the current PS APIs changed a lot compared to the ones against the app was compiled and Android 5 ships with this newer version (by now also 4.x devices will have the new version).

The great question now is how the PS handle backwards compatibility (app with old APIs requesting services from newer PS on device). It doesn't crash as I'm not receiving any automated crash reports. Maybe requests from the app are just silently ignored and thus we're not getting any new updates.

**Comment by mabnz** [comment]
Strangely, the subsequent location it's publishing is accurate, and
reflects my current location, even though the map within the app hasn't
updated in over 24 hours.

Secondly, it appears to be still publishing messages to
owntracks/username/<device id>, even though I've specified another topic to
publish to in the configuration (this happens in both the iOS and Android
app). I'm not sure if this is by-design, but I wonder if it's related to
the stale data.

**Comment by binarybucks** [comment]
What version are you seeing this on, the PS version or the APK from Github directly?

Also, what timestamp do the messages have? A current one or some time ago?

On iOS, older timestamp might be normal as it might queue messages. The Android app does not queue messages however.

**Comment by mabnz** [comment]
I've managed to work out the problem here. Originally when I set up the app
I had it publishing app updates to /owntracks/<name>/<device id>, and the
map reflected this by showing the location of this pointer. When I updated
where I wanted to publish to (owntracks/<name>) the map didn't quite get
this for a while, so had my location as static (when it was still updating
to the new publish url).

It's sorted itself out now, and it's actually working really well.

Hope this helps someone else.

**Comment by binarybucks** [comment]
The publish topic is changed immediately.
The subscribe topic obviously has to match but changes to it are only applied when you reconnect (better yet you restart the app).

I was always under the impression that no messages are received on the broker @jpmens?
--
Alexander Rust

**Comment by jpmens** [comment]
Ack @binarybucks
Over a distance of 50 km two (max 3) pubs. Not related to topic setting.

**Comment by mabnz** [comment]
Yes, come to think of it I think the issue was more related to my
subscription than my publish topic. I did try restarting the app multiple
times but that didn't appear to help.

**Comment by binarybucks** [comment]
Saw constant location updates every 2 minutes on my Nexus, so far so good. 
I'll prepare a Play Store beta this week for you to test out.

**Comment by mharizanov** [comment]
Great, can't wait to put it to work
Cheers
Martin

**Comment by jpmens** [comment]
@mharizanov FYI, beta will be hitting play store in an hour or so.

**Comment by mharizanov** [comment]
I don't seem to find the new version, the one in play store still says
"March 16, 2014"

Martin

**Comment by jpmens** [comment]
@mharizanov Play Store says 'OwnTracks Legacy' which is the old version.

Either sign up to beta through our Google+ community or just download apk from this repository in the `apk/` directory.

**Comment by binarybucks** [comment]
Sign up for the beta at https://play.google.com/apps/testing/org.owntracks.android and install org.owntracks.android from the app store. It is a seperate app. 

Please do not install the APK from this repository as you will not get any updated versions this way.

**Comment by mharizanov** [comment]
Link seems broken from here:

[image: Inline image 1]

**Comment by binarybucks** [comment]
You have to join the Google+ community first: https://plus.google.com/communities/102489112826520993343

That's the way the Google Play Beta System works.

**Comment by mharizanov** [comment]
Image seems broken, sending what I see:


*Sorry - nothing to see here.*

There may be several reasons:

   - The app you’re looking for doesn't exist
   - or
   - the app developer is not currently running a test
   - or
   - you are not eligible to participate in the testing program.

If you received the link to this page from someone, we recommend you
contact them for more information.

**Comment by mharizanov** [comment]
oh dear, silly me. got it.
Cheers
Martin

**Comment by binarybucks** [comment]
:+1:

**Comment by jpmens** [comment]
0.5.04 from Beta Store: over a distance of 24km (12 there, 12 back), two PUBs.

1. Leave event at 16:31 (which is correct)
2. Enter event at 17:00 (which is also correct)

Device was 'off'. I switch it on. Swipe-down shows "Disconnected". Open app, Prefs: "Disconnected".

**Comment by binarybucks** [comment]
What's your reporting interval in Reporting preferences? Default is 30 mim which would not have covered your 29 minute journey.

What is your background locator precision set to? If it's balanced, have you enable WiFi and Mobile network location in Android? 

Im asking because I found a post outlining that the fused locating provider is not working as advertised.

--
Alexander Rust

**Comment by jpmens** [comment]
Just changing that as we speak ...

Reporting interval was 15. I've now set to 5m.
Locator interval now set to: 10
Background accuracy: Balanced

Android location mode: High Accuracy (GPS, Wi-Fi, and cellular networks)

Will do this same drive at 19:30 today again.

**Comment by binarybucks** [comment]
Im browsing through a bug report against the fused location provider that is open and discussed since three years.

Could you reboot your device and drive the track again? 

If that doesn't work, please set the accuracy to high power (uses gps). There are reports that the network location provider gets stuck :/
--
Alexander Rust

**Comment by binarybucks** [comment]
For reference: https://code.google.com/p/android/issues/detail?id=57707

--
Alexander Rust

**Comment by jpmens** [comment]
Rebooting

**Comment by jpmens** [comment]
Better!

```
+--------+--------------------+---------------------+------+
| id     | topic              | tst                 | t    |
+--------+--------------------+---------------------+------+
| 129853 | owntracks/jpm/nex4 | 2015-02-25 18:35:30 | c    |
| 129931 | owntracks/jpm/nex4 | 2015-02-25 18:49:51 | -    |
| 129995 | owntracks/jpm/nex4 | 2015-02-25 18:53:52 | -    |
| 130053 | owntracks/jpm/nex4 | 2015-02-25 19:03:53 | -    |
| 130062 | owntracks/jpm/nex4 | 2015-02-25 19:15:39 | c    |
+--------+--------------------+---------------------+------+
```

**Comment by binarybucks** [comment]
Was that with reboot or high accuracy?

--
Alexander Rust

**Comment by jpmens** [comment]
Reporting interval  5m.
Locator interval set to: 10
Background accuracy: Balanced
Android location mode: High Accuracy (GPS, Wi-Fi, and cellular networks)
and reboot.

**Comment by binarybucks** [comment]
Crap, that would mean that we cannot really do something against this issue besides rebooting the device.


--
Alexander Rust

**Comment by jpmens** [comment]
I did this again. Route almost exactly the same, without  changing any settings and without rebooting since yesterday. Result:

```
+--------+--------------------+---------------------+------+
| id     | topic              | tst                 | t    |
+--------+--------------------+---------------------+------+
| 131328 | owntracks/jpm/nex4 | 2015-02-26 18:05:45 | c    |
| 131353 | owntracks/jpm/nex4 | 2015-02-26 18:05:45 | -    |
| 131361 | owntracks/jpm/nex4 | 2015-02-26 18:27:50 | -    |
| 131362 | owntracks/jpm/nex4 | 2015-02-26 18:28:37 | u    |
| 131369 | owntracks/jpm/nex4 | 2015-02-26 18:35:34 | -    |
| 131390 | owntracks/jpm/nex4 | 2015-02-26 18:35:34 | -    |
| 131410 | owntracks/jpm/nex4 | 2015-02-26 18:45:52 | -    |
| 131411 | owntracks/jpm/nex4 | 2015-02-26 18:56:20 | c    |
+--------+--------------------+---------------------+------+
8 rows in set (0.00 sec)
```

I note that at my destination (half way, at 18:27Z) I switched the phone on. Swipe-down said "connected", but my iOS hadn't received a PUB since 18:05Z from Android.

I opened the app: neither map, nor any locations (friends list empty). I PUBlished from iOS and nothing showed up in Android.

I published on Android, and immediate show on iOS.

Back at home now, I open the app: empty. (No locations received yet.)

The good news: waypoint events (enter/leave) appear to be quite reliable.

**Comment by binarybucks** [comment]
Waypoint events are out of question, they're somehow handled by a different backend. The tst is quite weird and I don't see a pattern. Do you?

I've added remote logging to the locator with 0.5.05 with {_type:"cmd", action:"debug"} which lets you dump an internal log of the Owntracks locator service via MQTT: Will upload it soon. 
Maybe this gets us to the root of the problen and if its Android or code related.

**Comment by binarybucks** [comment]
0.5.06 is on it's way. I've modified to the LocatorService to use a PendingIntent instead of a location listener so the service can be started by a location update. 

This version keeps track of 5000 lines of internal locator logging. When the remote dump command is enabled, two different reports can be gathered from the device by publishing a command to the base topic to which the device is subscribed (default owntracks/userid/deviceid).

- ```{_type:\"cmd\", action:\"dump\"}``` publishes internal state data of the application.  
- ```{_type:\"cmd\", action:\"dumpLog\"}``` publishes the locator log

Subscribe to the same topic before publishing the command, to receive the answer from the device. 

@jpmens can you make your drive (or another one) once more and post the output from both commands? I'm especially interested in new data when the service was restarted to find out if it is killed in the background.

**Comment by jpmens** [comment]
@binarybucks if this show up in beta playstore before 06:00 tomorrow, I'll take it for a 2x200 km drive.

**Comment by binarybucks** [comment]
Eta 1h

--
Alexander Rust

**Comment by binarybucks** [comment]
Another point that comes to my mind: 
Currently, there are several points to tweak that influence reporting. 

1. The locator settings influence how often the app receives updates. 
2. The pub interval influences if a received update is published. 

Considering the following timeline (t is time, u indicates a received location update at t).
U is influeced by the locator settings. P is influenced by the pub interval, so an update is published if an update is received and (currenttime - lastPublishTime) > pubInterval. 
```
  p                 p
  u        u        u
  _________________________________
t 1  2  3  4  5  6  7  8  9

```
With a pub interval of 4, the app will publish a location at 1, because lastPublishTime is 0. 
When an update is received at 4, no message will be published. When an update is received at 7, a message will be published because the time diff is not >> pubInterval. 


I propose to set a very low pubInterval and treat it more as an option to rate-limit messages.
The locator interval really is not the interval at which updates are received, but more of the max interval at which the OS guarantees updates (if everything works). More frequent updates might be received at any time.

**Comment by jpmens** [comment]
So pub interval 1, or is 0 possible?

What do you want me to set locator interval to?

**Comment by binarybucks** [comment]
Try 1

--
Alexander Rust

**Comment by jpmens** [comment]
I've set locator and pub interval each to 1 now. I'll report after the
200km tomorrow.

FYI 0.5.06 still says "no locations received yet"

**Comment by binarybucks** [comment]
Yes, there's some weirdness going on with #108 .

**Comment by jpmens** [comment]
I'm back at the ranch. This is what the device reported as soon as it smelled GSM after crossing the border: Distance travelleed during the online time: approx 100km

```
+--------+--------------------+---------------------+------+
| id     | topic              | tst                 | t    |
+--------+--------------------+---------------------+------+
| 135572 | owntracks/jpm/nex4 | 2015-03-01 10:29:03 | -    |
| 135581 | owntracks/jpm/nex4 | 2015-03-01 10:29:03 | -    |
| 135588 | owntracks/jpm/nex4 | 2015-03-01 10:35:05 | -    |
| 135629 | owntracks/jpm/nex4 | 2015-03-01 10:58:33 | -    |
| 135638 | owntracks/jpm/nex4 | 2015-03-01 11:05:39 | -    |
| 135641 | owntracks/jpm/nex4 | 2015-03-01 11:05:39 | -    |
| 135645 | owntracks/jpm/nex4 | 2015-03-01 11:08:43 | -    |
| 135648 | owntracks/jpm/nex4 | 2015-03-01 11:10:47 | -    |
| 135657 | owntracks/jpm/nex4 | 2015-03-01 11:15:43 | -    |
| 135662 | owntracks/jpm/nex4 | 2015-03-01 11:15:43 | -    |
| 135668 | owntracks/jpm/nex4 | 2015-03-01 11:23:54 | -    |
| 135670 | owntracks/jpm/nex4 | 2015-03-01 11:24:57 | -    |
| 135675 | owntracks/jpm/nex4 | 2015-03-01 11:24:57 | -    |
| 135680 | owntracks/jpm/nex4 | 2015-03-01 11:30:02 | -    |
| 135687 | owntracks/jpm/nex4 | 2015-03-01 11:31:07 | -    |
| 135695 | owntracks/jpm/nex4 | 2015-03-01 11:34:05 | -    |
| 135701 | owntracks/jpm/nex4 | 2015-03-01 11:36:09 | -    |
| 135706 | owntracks/jpm/nex4 | 2015-03-01 11:39:14 | -    |
| 135714 | owntracks/jpm/nex4 | 2015-03-01 11:45:21 | -    |
| 135717 | owntracks/jpm/nex4 | 2015-03-01 11:46:35 | c    |
+--------+--------------------+---------------------+------+
20 rows in set (0.02 sec)
```

### dump

```json
{
  "internal": {
    "locator": {
      "debug": {
        "debugRequestSmallestInterval": 500,
        "debugRequestInterval": 60000,
        "debugRequestDisplaycement": 500,
        "debugRequestPriority": 102,
        "debugLocationAPIConnectDate": "Sat Feb 28 13:33:02 GMT+01:00 2015",
        "debugLocatorServiceStartDate": "Sat Feb 28 13:33:02 GMT+01:00 2015"
      },
      "state": "INITIAL",
      "ready": "1",
      "foreground": "0",
      "lastKnownLocation": "52.0344114 : 8.476268",
      "lastPublishDate": 1425210395426,
      "waypointCount": 1,
      "hasLocationClient": "1",
      "hasLocationRequest": "1",
      "serviceCreationDate": "INITIAL"
    },
    "application": {
      "playServicesAvailable": "1"
    },
    "broker": {
      "state": "CONNECTED",
      "deferredPublishablesCount": 0,
      "keepAliveSeconds": 900
    }
  },
  "configuration": {
    "trackerId": "n4",
    "cleanSession": "1",
    "remoteConfiguration": "1",
    "sub": "1",
    "connectionAdvancedMode": "1",
    "pubIncludeBattery": "1",
    "auth": "1",
    "locatorInterval": "1",
    "locatorDisplacement": "500",
    "tlsCrtPath": "",
    "tls": "1",
    "_type": "configuration",
    "deviceId": "nex4crashl",
    "clientId": "jpm/nex4crashl",
    "host": "<redacted>",
    "port": "8883",
    "pubQos": "1",
    "keepalive": "60",
    "pubRetain": "1",
    "pub": "1",
    "pubInterval": "1",
    "pubTopicBase": "owntracks/jpm/nex4",
    "notification": "1",
    "notificationGeocoder": "1",
    "notificationLocation": "1",
    "notificationTickerOnPublish": "1",
    "tickerOnWaypointTransition": "1",
    "subTopic": "owntracks/+/+",
    "autostartOnBoot": "1",
    "locatorAccuracyBackground": "1",
    "locatorAccuracyForeground": "0",
    "beaconBackgroundScanPeriod": "30",
    "beaconForegroundScanPeriod": "30",
    "remoteCommandDump": "1",
    "remoteCommandReportLocation": "1"
  },
  "location": {
    "tid": "n4",
    "acc": "18.65",
    "tst": "1425212801",
    "lon": "8.476268",
    "lat": "52.0344114",
    "_type": "location"
  },
  "systemDate": "Sun Mar 01 13:27:13 GMT+01:00 2015",
  "_type": "dump"
}
```

### dumpLog

```
owntracks/jpm/nex4 {"_type":"cmd", "action":"dumpLog"}
owntracks/jpm/nex4 (null)
```

**Comment by binarybucks** [comment]
meh, empty dumpLog so that quick hack didn't work quite so well :D 
Good news is, that the service stays alive (debugLocatorServiceStartDate). 

Pubs look quite solid to me, don't they? The double pubs are a bit weird and will need further investigation though.

**Comment by jpmens** [comment]
Pubs look solid, yes and compare well to the pub frequency of our iOS app. And I've checked: those are duplicates (same lat/lon)

**Comment by binarybucks** [comment]
I guess you're not using that funny build of mosquitto 1.2 which liked to deliver message twice? :D

**Comment by jpmens** [comment]
Nope

**Comment by mabnz** [comment]
Hey guys,

Not to hijack an existing thread, but are there any tips for having the iOS
app update more frequently than once a day?

iOS 7.0. Location distance/time set to 25m/2 minutes respectively.

**Comment by jpmens** [comment]
@mabnz Please do not hijack this thread. If you have an issue, kindly open a ticket on the owntracks/ios repo, thanks.

**Comment by nevercast** [comment]
Is this still an active issue? 
I've not had an opportunity to fully test my android device with owntracks yet. But would be interested if this is a bug I can expect on Marshmellow.

**Comment by binarybucks** [comment]
Due to the fantastic state of Android fragmentation and the lack of updates
I cannot say that for sure as none of my test devices has received 6.x yet.
If you get your hands on an M device I'd be happy to hear from you how it
works especially regarding the new Doze mode.

Mit freundlichen Grüßen / With kind regards
Alexander Rust

On 25 Dec 2015, at 15:08, Josh Lloyd <notifications@github.com> wrote:

Is this still an active issue?
I've not had an opportunity to fully test my android device with owntracks
yet. But would be interested if this is a bug I can expect on Marshmellow.

—
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/86#issuecomment-167237645>.

**Comment by nevercast** [comment]
I'm using a Stock ROM Android M on my Nexus 5.

I'm currently running OwnTracks with Home Assistant and my own MQTT server. I will let you know how it goes. 

So far location reporting is frustrating. Foreground location is accurate, but background reports are highly inaccurate, at a scale of 1.5km uncertainty in Balanced power mode. With High power mode, OwnTracks waits constantly for occasionally location data, which causes Android to keep a constant GPS lock. If OwnTracks background interval is greater than ~2 minutes, OwnTracks Background Location should not keep a constant GPS lock, even in High Power mode in my opinion, or Balanced mode could be better balanced.

What is expected is that OwnTracks will open the Location service occasionally, wait for a strong long, and then publish the location. After which, closing the location service and going back to sleep. The lock can take up to a minute occasionally, but that's fine imo. Better than constant GPS usage. 

Without this high power GPS utilisation, the accuracy is too rough to be of use. A location accurate to 1500 meters is no good for home automation actions.

I'd be happy to try out any new features or beta releases. I'm currently not using a beta stream of OwnTracks.

**Comment by binarybucks** [comment]
Like I said before, we're at the mercy of the Android location service
blackbox. In general, balanced mode gives me and other users accurate
results (2-100m) when it can use known locations of WiFi SSIDs. Any chance
you have WiFi location or WiFi disabled in general?

As we have no control of when Android switches on or off the GPS, there is
nothing we can do to "balance" things. The only things we can tune are the
mode and displacement/interval.

Mit freundlichen Grüßen / With kind regards
Alexander Rust

On 25 Dec 2015, at 16:26, Josh Lloyd <notifications@github.com> wrote:

I'm using a Stock ROM Android M on my Nexus 5.

I'm currently running OwnTracks with Home Assistant and my own MQTT server.
I will let you know how it goes.

So far location reporting is frustrating. Foreground location is accurate,
but background reports are highly inaccurate, at a scale of 1.5km
uncertainty in Balanced power mode. With High power mode, OwnTracks waits
constantly for occasionally location data, which causes Android to keep a
constant GPS lock. If OwnTracks background interval is greater than ~2
minutes, OwnTracks Background Location should not keep a constant GPS lock,
even in High Power mode in my opinion, or Balanced mode could be better
balanced.

What is expected is that OwnTracks will open the Location service
occasionally, wait for a strong long, and then publish the location. After
which, closing the location service and going back to sleep. The lock can
take up to a minute occasionally, but that's fine imo. Better than constant
GPS usage.

Without this high power GPS utilisation, the accuracy is too rough to be of
use. A location accurate to 1500 meters is no good for home automation
actions.

I'd be happy to try out any new features or beta releases. I'm currently
not using a beta stream of OwnTracks.

—
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/86#issuecomment-167245306>.

**Comment by nevercast** [comment]
I have WiFi enabled, and as far as I can tell I have WiFi location enabled. Currently when running in the background Owntracks says ( In the notification ) that I'm two streets over. Which falls outside of my home perimeter. 

I will check my settings on my phone to ensure that WiFi location is certainly working. It's strange that when there is no GPS signal I am placed nearly 400 meters away, with an accuracy of 1.5km.

**Comment by binarybucks** [comment]
> with an accuracy of 1.5km.
Your phone is using the Cell Tower location instead of WiFi to locate you then. Please ensure that you have WiFi assisted location enabled on your device and your WiFi SSID doesn't end with `_nomap` (see https://support.google.com/nexus/answer/1725632?hl=en)

**Comment by nevercast** [comment]
Both are enabled and my Access Point nor my neighbours ends in _nomap. 
Not sure why the issue was closed consider that it isn't resolved. 

I'm installing Android Studio now. I'll look at the location code and see if I can offer any changes.

**Comment by binarybucks** [comment]
sorry to confuse you. The issue was closed because it's not related to the
ones reported previously. In those cases, no locations were reported at
all. Could you please open a new issue with your findings so we can
continue to discuss the issue?

One thing that might help is updating the Play Service dependencies. It's
currently using version 7.x instead of 8.x so maybe some location things
have improved since then. I'll include the new version with the next
release.

In the meantime, please try the latest 0.5.x tag in Android Studio and not
the master branch. If you need any assistant, please let me know in a new
issue as mentioned.

Mit freundlichen Grüßen / With kind regards
Alexander Rust

On 28 Dec 2015, at 01:34, Josh Lloyd <notifications@github.com> wrote:

Both are enabled and my Access Point nor my neighbours ends in _nomap.
Not sure why the issue was closed consider that it isn't resolved.

I'm installing Android Studio now. I'll look at the location code and see
if I can offer any changes.

—
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/86#issuecomment-167450728>.
